Repository AY2324S1-CS2103-T16-1/tp, pull requests merged in 2023-11, with the labels that each got.

#64 Filter feature
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ManageHrParser.java
  src/main/java/seedu/address/model/employee/ContainsDepartmentPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ManageHrParserTest.java
  src/test/java/seedu/address/model/employee/ContainsDepartmentPredicateTest.java
Labels: type.Story, priority.High

#63 Add manager v1.3
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ManageHr.java
  src/main/java/seedu/address/model/employee/Address.java
  src/main/java/seedu/address/model/employee/Employee.java
  src/main/java/seedu/address/model/employee/Role.java
  src/main/java/seedu/address/model/employee/UniqueEmployeeList.java
  src/main/java/seedu/address/model/employee/exceptions/DuplicateEmployeeException.java
  src/main/java/seedu/address/model/employee/exceptions/EmployeeNotFoundException.java
  src/main/java/seedu/address/model/employee/exceptions/InvalidRoleException.java
  src/main/java/seedu/address/model/employee/exceptions/ModelException.java
  src/main/java/seedu/address/model/employee/exceptions/SubordinatePresentException.java
  src/main/java/seedu/address/model/employee/exceptions/SupervisorNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEmployee.java
  src/main/java/seedu/address/storage/JsonAdaptedSupervisor.java
  src/main/java/seedu/address/storage/JsonManageHrStorage.java
  src/main/java/seedu/address/storage/JsonSerializableManageHr.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonManageHrStorageTest/invalidAndValidEmployeeManageHr.json
  src/test/data/JsonManageHrStorageTest/invalidEmployeeManageHr.json
  src/test/data/JsonSerializableManageHrTest/duplicateEmployeeManageHr.json
  src/test/data/JsonSerializableManageHrTest/invalidEmployeeManageHr.json
  src/test/data/JsonSerializableManageHrTest/typicalEmployeesManageHr.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEmployeeDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/employee/EmployeeTest.java
  src/test/java/seedu/address/model/employee/RoleTest.java
  src/test/java/seedu/address/model/employee/UniqueEmployeeListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java
  src/test/java/seedu/address/testutil/EditEmployeeDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EmployeeBuilder.java
  src/test/java/seedu/address/testutil/EmployeeUtil.java
  src/test/java/seedu/address/testutil/TypicalEmployees.java
Labels: enhancement

#70 Implement `d/` department prefix for `filter` feature
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ManageHrParserTest.java
Labels: type.Enhancement, priority.High

#72 Enhance filter feature with salary prefix
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/employee/ContainsDepartmentPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ManageHrParserTest.java
  src/test/java/seedu/address/model/employee/ContainsDepartmentPredicateTest.java
Labels: type.Enhancement, priority.High

#75 UserGuide update (filter feature)
  docs/UserGuide.md
  docs/images/filterCommandExample.png
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#76 Filter with multiple prefixes v1.3
  src/main/java/seedu/address/commons/util/CustomSet.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/employee/ContainsAllPredicate.java
  src/main/java/seedu/address/model/employee/ContainsDepartmentPredicate.java
  src/main/java/seedu/address/model/employee/Salary.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ManageHrParserTest.java
  src/test/java/seedu/address/model/employee/ContainsAllPredicateTest.java
  src/test/java/seedu/address/model/employee/ContainsDepartmentPredicateTest.java
Labels: enhancement

#134 Update PPP draft
  docs/team/kenvynkwek.md
Labels: type.Task, priority.High

#140 Fix bug stopping ManageHR from launch
  src/main/java/seedu/address/model/ManageHr.java
  src/main/java/seedu/address/model/employee/UniqueEmployeeList.java
  src/main/java/seedu/address/storage/JsonSerializableManageHr.java
Labels: bug

#136 v1.4 code changes
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/employee/ContainsAllPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/employee/ContainsAllPredicateTest.java
Labels: type.Task, priority.High

#144 v1.4 documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterCommandClassDiagram.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterCommandClassDiagram.png
  docs/images/Ui.png
  docs/images/filterCommandExample.png
  docs/images/listDisplay.png
  docs/team/kenvynkwek.md
Labels: type.Task, priority.High

#147 Update DG Filter Activity Diagram
  docs/DeveloperGuide.md
  docs/diagrams/FilterActivityDiagramPart1.puml
  docs/diagrams/FilterActivityDiagramPart2.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterActivityDiagramPart1.png
  docs/images/FilterActivityDiagramPart2.png
Labels: type.Task, priority.High
