Repository AY2324S1-CS2103-T16-1/tp, pull requests merged in 2023-10, with the labels that each got.

#7 Update Jekyll Sitewide Settings
  docs/AboutUs.md
  docs/_sass/minima/_base.scss
  docs/images/sungmatt.png
Labels: documentation

#6 Add Matthew into developer team
  docs/AboutUs.md
  docs/images/sungmatt.png
Labels: documentation

#18 Include skeletal Project Portfolio Page
  docs/team/zhuxihua.md
Labels: documentation

#20 Modify profile in AboutUs.md
  docs/AboutUs.md
  docs/images/xihuaz.png
  docs/team/xihuaz.md
Labels: documentation

#30 Modify DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#36 Fix typo in UG
  docs/UserGuide.md
Labels: documentation

#37 Modify tag to department
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/department/Department.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDepartment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#39 Refactor: Rename AddressBook to ManageHR
  data/managehr.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/ManageHrParser.java
  src/main/java/seedu/address/model/ManageHr.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyManageHr.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonManageHrStorage.java
  src/main/java/seedu/address/storage/JsonSerializableManageHR.java
  src/main/java/seedu/address/storage/ManageHrStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ManageHrParserTest.java
  src/test/java/seedu/address/model/ManageHrTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonManageHrStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableManageHrTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#49 Revamped UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ProfileDetails.java
  src/main/java/seedu/address/ui/Sidebar.java
  src/main/resources/images/location_icon.png
  src/main/resources/images/mail_icon.png
  src/main/resources/images/money_icon.png
  src/main/resources/images/phone_icon.png
  src/main/resources/images/phonebook_icon.png
  src/main/resources/images/user_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ProfileDetails.fxml
  src/main/resources/view/Sidebar.fxml
Labels: type.Epic, priority.High

#55 Update for v1.3.trial JAR release
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#57 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/images/ManageHR/ListCommandSequenceDiagram.png
Labels: documentation

#58 Update DG with `filter` command details
  docs/DeveloperGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/images/FilterActivityDiagram.png
Labels: type.Task, priority.High
